---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: plugins/hugo
    settings:
      hugo_version: 0.70.0
      validate: true

  - name: publish on s3
    image: plugins/s3
    settings:
      endpoint: https://storage.nemunai.re
      path_style: true
      bucket: happydomain-htdocs
      access_key:
        from_secret: s3_access_key
      secret_key:
        from_secret: s3_secret_key
      source: public/**/*
      strip_prefix: public/
      target: /${DRONE_BRANCH//\//-}

trigger:
  event:
  - cron
  - push
  - tag
