when:
  event:
    - push
    - tag
    - cron

steps:
  build:
    image: registry.nemunai.re/plugins/hugo
    settings:
      hugo_version: 0.119.0

  deploy-on-ovh:
    image: nemunaire/drone-ftps
    settings:
      hostname: ftp.cluster021.hosting.ovh.net
      ftp_username:
        from_secret: ovh_ftp_username
      ftp_password:
        from_secret: ovh_ftp_password
      clean_dir: true
      pre_action: 'ftp:passive-mode true'
      secure: false
      src_dir: /public/
      dest_dir: /www/

  publish-on-s3:
    image: woodpeckerci/plugin-s3
    settings:
      endpoint: https://storage.nemunai.re
      path_style: true
      bucket: happydomain-htdocs
      access_key:
        from_secret: s3_access_key
      secret_key:
        from_secret: s3_secret_key
      source: public/**/*
      strip_prefix: public/
      target: "/${CI_COMMIT_BRANCH//\\//-}"
