when:
  event:
    - push
    - tag
    - cron

steps:
  - name: build
    image: hugomods/hugo:base
    commands:
      - hugo
    environment:
      HUGO_ENVIRONMENT: production

  - name: deploy on ovh
    image: nemunaire/drone-ftps
    settings:
      hostname: ftp.cluster021.hosting.ovh.net
      ftp_username:
        from_secret: ovh_ftp_username
      ftp_password:
        from_secret: ovh_ftp_password
      clean_dir: true
      pre_action: 'set ftp:passive-mode true'
      secure: false
      src_dir: /public/
      dest_dir: /www/
    when:
      - branch: master
        event:
          - cron
          - push
          - tag
