title: "happyDomain"
baseURL: "https://www.happydomain.org/"

defaultContentLanguageInSubdir: true
removePathAccents: true

author:
  name: "happyDNS team"
  framagit: "happyDomain/"

languages:
  en:
    title: "happyDomain. Finally a simple interface for domain names."
    weight: 1

  fr:
    title: "happyDomain. L'interface des noms de domaines."
    weight: 2

    menu:
      main:
      - identifier: "features"
        name: "Fonctionnalités"
        url: "/fr/#features"
        weight: 10

      - identifier: "downloads"
        name: "Téléchargements"
        url: "/fr/#downloads"
        weight: 20

      - identifier: "blog"
        name: "Blog"
        url: "https://blog.happydomain.org/fr/"
        weight: 30

    params:
      others_links:
      - text: "S'inscrire"
        href: "/join"
        class: "btn btn-secondary"
        icon: "bi-person-plus-fill"
      - text: "S'identifier"
        href: "/login"
        class: "btn btn-outline-primary"
        icon: "bi-person-check-fill"

      carousel:
      - title: "domains-lists"
        description: "**Page d'accueil:** liste des domaines, de différents hébergeurs"
        image: "/img/screenshots/domains-list.png"

      - title: "domain-abstract"
        description: "Une zone simplifiée"
        image: "/img/screenshots/domain-abstract.png"

      - title: "domain-abstract-list"
        description: "Une zone simplifiée, sous forme de liste, plus rapide à modifier"
        image: "/img/screenshots/domain-abstract-list.png"

      - title: "zone-diff"
        description: "Liste les changements avant d'appliquer les modifications"
        image: "/img/screenshots/zone-diff.png"

      - title: "domain-records"
        description: "Les enregistrements d'une zone, modifiable depuis l'interface"
        image: "/img/screenshots/domain-records.png"

      - title: "domain-source"
        description: "Informations sur la source"
        image: "/img/screenshots/domain-source.png"

      - title: "sources"
        description: "Liste des sources existantes où récupérer les domaines"
        image: "/img/screenshots/sources.png"

params:
  newsletter: "newsletter@happydns.org"
  tryit: "https://try.happydomain.org/"

  others_links:
  - text: "Sign up"
    href: "/join"
    class: "btn btn-secondary"
    icon: "bi-person-plus-fill"
  - text: "Sign in"
    href: "/login"
    class: "btn btn-outline-primary"
    icon: "bi-person-check-fill"

  carousel:
  - title: "domains-lists"
    description: "**Home page:** domains list on dedicated provider"
    image: "/img/screenshots/domains-list.png"

  - title: "domain-abstract"
    description: "Simplified zone: records grouped by services"
    image: "/img/screenshots/domain-abstract.png"

  - title: "domain-abstract-list"
    description: "Simplified zone in list, for quicker editing"
    image: "/img/screenshots/domain-abstract-list.png"

  - title: "zone-diff"
    description: "Display zone diff before applying changes"
    image: "/img/screenshots/zone-diff.png"

  - title: "domain-records"
    description: "Resource records for a zone: editable through happyDomain"
    image: "/img/screenshots/domain-records.png"

  - title: "domain-source"
    description: "Information about the source"
    image: "/img/screenshots/domain-source.png"

  - title: "sources"
    description: "Existing sources where pull domains"
    image: "/img/screenshots/sources.png"

menu:
  main:
  - identifier: "features"
    name: "Features"
    url: "/en/#features"
    weight: 10

  - identifier: "downloads"
    name: "Downloads"
    url: "/en/#downloads"
    weight: 20

  - identifier: "News"
    name: "Blog"
    url: "https://blog.happydomain.org/"
    weight: 30

markup:
  goldmark:
    renderer:
      unsafe: true

outputs:
  home: [ "HTML", "RSS" ]
