title: "happyDomain"
baseURL: "https://www.happydomain.org/"

defaultContentLanguageInSubdir: true
removePathAccents: true

author:
  name: "happyDNS team"
  framagit: "happyDomain/"

languages:
  en:
    title: "happyDomain. Finally a simple interface for domain names."
    weight: 1

  fr:
    title: "happyDomain. L'interface des noms de domaines."
    weight: 2

    menu:
      main:
      - identifier: "features"
        name: "Fonctionnalités"
        url: "/fr/#features"
        weight: 10

      - identifier: "downloads"
        name: "Téléchargements"
        url: "/fr/#downloads"
        weight: 20

      - identifier: "blog"
        name: "Blog"
        url: "https://blog.happydomain.org/fr/"
        weight: 30

    params:
      DefaultDescription: "L'interface des noms de domaines."

      others_links:
      - text: "S'inscrire"
        href: "//app.happydomain.org/join"
        class: "btn btn-secondary"
        icon: "bi-person-plus-fill"
      - text: "S'identifier"
        href: "//app.happydomain.org/login"
        class: "btn btn-outline-primary"
        icon: "bi-person-check-fill"

      carousel:
      - title: "domains-lists"
        description: "**Page d'accueil:** liste des domaines, de différents hébergeurs"
        image: "/img/screenshots/domains-list.webp"

      - title: "domain-abstract"
        description: "Une zone simplifiée"
        image: "/img/screenshots/domain-abstract.webp"

      - title: "service-caa"
        description: "Des formulaires clairs vous aident pour choisir les meilleurs paramètres"
        image: "/img/screenshots/service-caa.webp"

      - title: "zone-diff"
        description: "Liste les changements avant d'appliquer les modifications"
        image: "/img/screenshots/zone-diff.webp"

      - title: "domain-history"
        description: "Retrouvez tous vos changements en un coup d'œil"
        image: "/img/screenshots/domain-history.webp"

      - title: "domain-services"
        description: "Ajoutez facilement de nouveaux usages à vos zones"
        image: "/img/screenshots/domain-services.webp"

      - title: "domain-logs"
        description: "Le journal d'action de la zone garde un trace de qui à fait quoi, quand"
        image: "/img/screenshots/domain-logs.webp"

      - title: "domain-abstract-list"
        description: "Une zone simplifiée, sous forme de liste, plus rapide à modifier"
        image: "/img/screenshots/domain-abstract-list.webp"

      - title: "sources"
        description: "Liste des sources existantes où récupérer les domaines"
        image: "/img/screenshots/sources.png"

params:
  DefaultDescription: "Finally a simple interface for domain names."
  newsletter: "newsletter@happydns.org"
  survey: "https://feedback.happydomain.org/"
  tryit: "https://try.happydomain.org/"

  others_links:
  - text: "Sign up"
    href: "//app.happydomain.org/join"
    class: "btn btn-secondary"
    icon: "bi-person-plus-fill"
  - text: "Sign in"
    href: "//app.happydomain.org/login"
    class: "btn btn-outline-primary"
    icon: "bi-person-check-fill"

  carousel:
  - title: "domains-lists"
    description: "**Home page:** domains list on dedicated provider"
    image: "/img/screenshots/domains-list.webp"

  - title: "domain-abstract"
    description: "Simplified zone: records grouped by services"
    image: "/img/screenshots/domain-abstract.webp"

  - title: "service-caa"
    description: "Clear forms help you choose the best settings"
    image: "/img/screenshots/service-caa.webp"

  - title: "zone-diff"
    description: "Display zone diff before applying changes"
    image: "/img/screenshots/zone-diff.webp"

  - title: "domain-history"
    description: "All your changes at a glance"
    image: "/img/screenshots/domain-history.webp"

  - title: "domain-services"
    description: "Easily add new uses to your zones"
    image: "/img/screenshots/domain-services.webp"

  - title: "domain-logs"
    description: "The zone action log keeps track of who did what, when"
    image: "/img/screenshots/domain-logs.webp"

  - title: "domain-abstract-list"
    description: "Simplified zone in list, for quicker editing"
    image: "/img/screenshots/domain-abstract-list.webp"

  - title: "sources"
    description: "Existing sources where pull domains"
    image: "/img/screenshots/sources.png"

menu:
  main:
  - identifier: "features"
    name: "Features"
    url: "/en/#features"
    weight: 10

  - identifier: "downloads"
    name: "Downloads"
    url: "/en/#downloads"
    weight: 20

  - identifier: "News"
    name: "Blog"
    url: "https://blog.happydomain.org/"
    weight: 30

markup:
  goldmark:
    renderer:
      unsafe: true

outputs:
  home: [ "HTML", "RSS" ]
