title = "happyDNS"
baseURL = "https://www.happydns.org/"

defaultContentLanguageInSubdir = true
removePathAccents = true

[Author]
  name = "happyDNS team"
  framagit = "happyDNS/"

[languages]
  [languages.en]
    title = "happyDNS. Finally a simple interface for domain names."
    weight = 1

  [languages.fr]
    title = "happyDNS. L'interface des noms de domaines."
    weight = 2
    [languages.fr.menu]
      [[languages.fr.menu.main]]
        identifier = "features"
        name = "Fonctionnalités"
        url = "/fr/#features"
        weight = 10

      [[languages.fr.menu.main]]
        identifier = "downloads"
        name = "Téléchargements"
        url = "/fr/#downloads"
        weight = 20

#      [[languages.fr.menu.main]]
#        identifier = "blog"
#        name = "Blog"
#        url = "https://blog.happydns.org/"
#        weight = 30

    [languages.fr.params]
      [[languages.fr.params.carousel]]
        title = "domains-lists"
        description = "**Page d'accueil:** liste des domaines, de différents hébergeurs"
        image = "/img/screenshots/domains-list.png"

      [[languages.fr.params.carousel]]
        title = "domain-abstract"
        description = "Une zone simplifiée"
        image = "/img/screenshots/domain-abstract.png"

      [[languages.fr.params.carousel]]
        title = "domain-abstract-list"
        description = "Une zone simplifiée, sous forme de liste, plus rapide à modifier"
        image = "/img/screenshots/domain-abstract-list.png"

      [[languages.fr.params.carousel]]
        title = "zone-diff"
        description = "Liste les changements avant d'appliquer les modifications"
        image = "/img/screenshots/zone-diff.png"

      [[languages.fr.params.carousel]]
        title = "domain-records"
        description = "Les enregistrements d'une zone, modifiable depuis l'interface"
        image = "/img/screenshots/domain-records.png"

      [[languages.fr.params.carousel]]
        title = "domain-source"
        description = "Informations sur la source"
        image = "/img/screenshots/domain-source.png"

      [[languages.fr.params.carousel]]
        title = "sources"
        description = "Liste des sources existantes où récupérer les domaines"
        image = "/img/screenshots/sources.png"

[params]
newsletter = "newsletter@happydns.org"
tryit = "/join"

  [[params.carousel]]
    title = "domains-lists"
    description = "**Home page:** domains list on dedicated provider"
    image = "/img/screenshots/domains-list.png"

  [[params.carousel]]
    title = "domain-abstract"
    description = "Simplified zone: records grouped by services"
    image = "/img/screenshots/domain-abstract.png"

  [[params.carousel]]
    title = "domain-abstract-list"
    description = "Simplified zone in list, for quicker editing"
    image = "/img/screenshots/domain-abstract-list.png"

  [[params.carousel]]
    title = "zone-diff"
    description = "Display zone diff before applying changes"
    image = "/img/screenshots/zone-diff.png"

  [[params.carousel]]
    title = "domain-records"
    description = "Resource records for a zone: editable through happyDNS"
    image = "/img/screenshots/domain-records.png"

  [[params.carousel]]
    title = "domain-source"
    description = "Information about the source"
    image = "/img/screenshots/domain-source.png"

  [[params.carousel]]
    title = "sources"
    description = "Existing sources where pull domains"
    image = "/img/screenshots/sources.png"

[menu]
  [[menu.main]]
    identifier = "features"
    name = "Features"
    url = "/en/#features"
    weight = 10

  [[menu.main]]
    identifier = "downloads"
    name = "Downloads"
    url = "/en/#downloads"
    weight = 20

#  [[menu.main]]
#    identifier = "blog"
#    name = "Blog"
#    url = "https://blog.happydns.org/"
#    weight = 30

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[outputs]
  home = [ "HTML", "RSS" ]
